[package]
name = "program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-program = "1.9.9"
common = { path = "../common" }
borsh = "0.9.0"
borsh-derive = "0.9.0"
