[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45"
solana-sdk = "1.9.7"
solana-client = "1.9.7"
solana-cli-config = "1.9.7"
log = "0.4.14"
env_logger = "0.9.0"
clap = { version = "3.0.14", features = ["derive"] }
common = { path = "../common" }